# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/afm/all/afm.rbi
#
# afm-0.2.2

module AFM
end
class AFM::Font
  def [](key); end
  def char_metrics; end
  def char_metrics_by_code; end
  def initialize(filename); end
  def kern_pairs; end
  def metadata; end
  def metrics_for(char); end
  def self.from_file(file); end
end
