# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `afm` gem.
# Please instead update this file by running `bin/tapioca gem afm`.

# source://afm//lib/afm.rb#1
module AFM; end

# source://afm//lib/afm.rb#34
class AFM::Font
  # Loading a Font Metrics file by absolute path (no automatic font path resolution)
  #
  # @return [Font] a new instance of Font
  #
  # source://afm//lib/afm.rb#38
  def initialize(filename); end

  # Get metadata by key
  #
  # source://afm//lib/afm.rb#88
  def [](key); end

  # Returns the value of attribute char_metrics.
  #
  # source://afm//lib/afm.rb#35
  def char_metrics; end

  # Returns the value of attribute char_metrics_by_code.
  #
  # source://afm//lib/afm.rb#35
  def char_metrics_by_code; end

  # Returns the value of attribute kern_pairs.
  #
  # source://afm//lib/afm.rb#35
  def kern_pairs; end

  # Returns the value of attribute metadata.
  #
  # source://afm//lib/afm.rb#35
  def metadata; end

  # Get metrics for character. Takes an integer (charcode) or
  # a one-char string. currently works only for Latin1 strings,
  # since we only have a chartable for the Latin1 charset so far.
  # (shamelessly stolen from AFM.pm by Gisle Aas)
  #
  # source://afm//lib/afm.rb#96
  def metrics_for(char); end

  class << self
    # alias for new()
    #
    # source://afm//lib/afm.rb#82
    def from_file(file); end
  end
end

# source://afm//lib/afm.rb#3
AFM::ISO_LATIN1_ENCODING = T.let(T.unsafe(nil), Array)
