# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ascii85_native` gem.
# Please instead update this file by running `bin/tapioca gem ascii85_native`.

# source://ascii85_native//lib/ascii85_native.rb#5
module Ascii85Native
  extend ::FFI::Library

  def a85_decode(*_arg0); end
  def a85_decoded_size(*_arg0); end
  def a85_encode(*_arg0); end
  def a85_encoded_size(*_arg0); end

  class << self
    def a85_decode(*_arg0); end
    def a85_decoded_size(*_arg0); end
    def a85_encode(*_arg0); end
    def a85_encoded_size(*_arg0); end

    # source://ascii85_native//lib/ascii85_native.rb#51
    def decode(input, force_delimiter = T.unsafe(nil)); end

    # source://ascii85_native//lib/ascii85_native.rb#22
    def encode(input, include_delimiter = T.unsafe(nil)); end

    # source://ascii85_native//lib/ascii85_native.rb#94
    def find_stream_end(input); end

    # source://ascii85_native//lib/ascii85_native.rb#75
    def find_stream_start(input); end
  end
end
