# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ascii85_native/all/ascii85_native.rbi
#
# ascii85_native-1.0.3

module Ascii85Native
  def a85_decode(*arg0); end
  def a85_decoded_size(*arg0); end
  def a85_encode(*arg0); end
  def a85_encoded_size(*arg0); end
  def self.a85_decode(*arg0); end
  def self.a85_decoded_size(*arg0); end
  def self.a85_encode(*arg0); end
  def self.a85_encoded_size(*arg0); end
  def self.decode(input, force_delimiter = nil); end
  def self.encode(input, include_delimiter = nil); end
  def self.find_stream_end(input); end
  def self.find_stream_start(input); end
  extend FFI::Library
end
