# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-rc4/all/ruby-rc4.rbi
#
# ruby-rc4-0.1.5

class RC4
  def decrypt(text); end
  def encrypt!(text); end
  def encrypt(text); end
  def initialize(str); end
  def process(text); end
  def round; end
end
