# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-rc4` gem.
# Please instead update this file by running `bin/tapioca gem ruby-rc4`.

# source://ruby-rc4//lib/rc4.rb#1
class RC4
  # @return [RC4] a new instance of RC4
  #
  # source://ruby-rc4//lib/rc4.rb#3
  def initialize(str); end

  # source://ruby-rc4//lib/rc4.rb#24
  def decrypt(text); end

  # source://ruby-rc4//lib/rc4.rb#24
  def encrypt(text); end

  # source://ruby-rc4//lib/rc4.rb#20
  def encrypt!(text); end

  private

  # source://ruby-rc4//lib/rc4.rb#32
  def process(text); end

  # source://ruby-rc4//lib/rc4.rb#36
  def round; end
end
