agents:
  queue: hosted

steps:
  - command: "auto/run-sorbet"
    label: ":sorbet:"
    key: sorbet
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "3.4"

  - command: "auto/run-require-strict-typing"
    label: "typed: strict"
    key: strict-typing
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "3.4"

  - command: "auto/run-quality"
    label: "quality"
    key: quality
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "3.4"

  - command: "auto/run-specs"
    label: "rspec ({{matrix}})"
    key: specs-legacy
    depends_on:
      - quality
      - sorbet
      - strict-typing
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "{{matrix}}"
      BUNDLE_GEMFILE: "/work/Gemfile-legacy"
    matrix:
      - "2.1"
      - "2.2"
      - "2.3"
      - "2.4"
      - "2.5"
      - "2.6"
      - "2.7"
      - "3.0"
      - "3.1"

  - command: "auto/run-specs"
    label: "rspec ({{matrix}})"
    key: specs
    depends_on:
      - quality
      - sorbet
      - strict-typing
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "{{matrix}}"
    matrix:
      - "3.2"
      - "3.3"
      - "3.4"
      - "4.0"

  - command: "auto/run-specs"
    label: "rspec (jruby-{{matrix}})"
    key: specs-jruby
    depends_on:
      - quality
      - sorbet
      - strict-typing
    env:
      DOCKER_IMAGE: "jruby"
      RUBY_VERSION: "{{matrix}}"
      BUNDLE_GEMFILE: "/work/Gemfile-legacy"
    matrix:
      - "9.1"
      - "9.2"
      - "9.3"
      - "9.4"
      - "10.0"

  - command: "auto/run-specs"
    label: "rpsec (truffleruby-{{matrix}})"
    key: specs-truffleruby
    depends_on:
      - quality
      - sorbet
      - strict-typing
    soft_fail: true
    matrix:
      - "33.0.1"
    env:
      DOCKER_IMAGE: "truffleruby"
      RUBY_VERSION: "{{matrix}}"
      BUNDLE_GEMFILE: "/work/Gemfile-legacy"


  - command: "auto/upload-release-steps"
    label: "release?"
    key: upload-release
    depends_on:
      - specs
      - specs-legacy
      - specs-jruby
    branches: main
