agents:
  queue: hosted

steps:
  - command: "auto/run-sorbet"
    label: ":sorbet:"
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "3.1"

  - command: "auto/run-require-strict-typing"
    label: "typed: strict"
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "3.1"

  - command: "auto/run-quality"
    label: "quality"
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "3.1"

  - wait

  - command: "auto/run-specs"
    label: "rspec ({{matrix}})"
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "{{matrix}}"
      BUNDLE_GEMFILE: "/work/Gemfile-legacy"
    matrix:
      - "2.0"
      - "2.1"
      - "2.2"
      - "2.3"
      - "2.4"
      - "2.5"
      - "2.6"
      - "2.7"

  - command: "auto/run-specs"
    label: "rspec ({{matrix}})"
    env:
      DOCKER_IMAGE: "ruby"
      RUBY_VERSION: "{{matrix}}"
    matrix:
      - "3.0"
      - "3.1"
      - "3.2"
      - "3.3"
      - "3.4"

  - command: "auto/run-specs"
    label: "rspec (jruby-{{matrix}})"
    env:
      DOCKER_IMAGE: "jruby"
      RUBY_VERSION: "{{matrix}}"
      BUNDLE_GEMFILE: "/work/Gemfile-legacy"
    matrix:
      - "9.1"
      - "9.2"
      - "9.3"

  - command: "auto/run-specs"
    label: "rspec (jruby-{{matrix}})"
    env:
      DOCKER_IMAGE: "jruby"
      RUBY_VERSION: "{{matrix}}"
    soft_fail: true
    matrix:
      - "9.4"
